language: node_js
node_js:
- '18'
before_script:
- cd integration-tests && npm install
script: cd integration-tests && npm test
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: modernagile@gmail.com
  password:
    secure: juJo3P+zH9jPiE8U9SzRplqZVvbSVLquAiaY7vR3Z47ZqmpTUBcdLXJloTDQJGraYpdybSNsQMNkzOXeAIS6epILnFsnVMvpaHGYPcVyAcet2FCmayoBlPVZJs8kP0TyCdc9RI4/LiRoQnSJqZ4OZRZ7po/yIhHRJfh4lcvJk4iLBf24iWXRlPiZ59x7P/U7hELB7vMK4w7t+L0p5ygYrq4rIXDyd1Kuyq/BpTX05gX1RGy17SQgIW/thg1UaIKeLkdlXYspr4T7onAHL9/TEMryRFwI6F23GZ3dWusbCvvUdQpkleRsMgzJYL3xrSibQrK/17IW7ZhmAvgi9HLyxlztKTTFmT+gh15I50RPMbzw+DmPXdFgpd6PkUu1DHtGNLgGncmwgIZHEsKQ02vniKb8MQXvjpbimC50uuZi39Qoa+pghsXl6bRnRC37e7nM11Y0xT5syT+C8LOVrTmAFeYaQNsoZUvgYJjpK7ivOHfs3oyvbLoT2EM62wCXMxK+zwE9P4oW5l6YR3cEor+wTrzdP8uVm56OjzinNZLqElZasbO2k2guisovqwBwAPnpBktK37A3dZ3Ew1QxoP346Ql0XuANHVMV1e5wI0tL7doWaTXd35oqyYczu0h6yHmKvHqEr+j/njKLtF8320cjNdk863bk4fw70OWT0m4uRY8=
  organization: Modern Agile
  space: development
  on:
    repo: modernagile/modernagile.github.io
