language: node_js
node_js:
- '6'
before_script:
- npm install -g grunt
- npm install -g grunt-contrib-qunit --save-dev
script: grunt --base tests --gruntfile tests/Gruntfile.js
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: modernagile@gmail.com
  password:
    secure: uozZKGVR6nG/hktQYnmUY755Q+9h3/Ss+OskXVN5Wv4ofjJGArLcSFKgSBMKeKmIRyA+Ck1cFgmdd16ddbipxTdFqe+ePFV8v42z1EyxM4IDUK0garOxXNXgbRmrtHO0NO9cI4tHf9XAYbI65RtN5kShHGW1gE5ukmIEtj+IiO7MJqD+hAllyTWz1HxagqUYMOsEmifFYR18DUEt5ciSxWifvxKN/4UFu+7V3GnT+Fz+EBo7VZ480O4E/fEtyYcyRzhVw/11NGdYSRBPIXD4Nl1gj2rjrKcbZDhacKqlvWtHr4CGG0RGQQnHpjeWJD25voVHCppS9U+iw4K7hI4FHmtevDEDok7md1GGODHYAAdx1Na6Qs3wp6SpVK29+XlCMUYKsEfIiF+tv9x/6ZWa5I6b+MBIIXdmuXB5+EeP4s0SUuw/wvEi4kOk97Qy7jLbAjxYD8Z7jflq23HV9kfTPAC2MmZlxKeR+DmWT0m6T1XLuWwTwtL7zVIgP8bSMvjYJ1ETzDwi47PwlfTt1ixlkUiQ73KsrPz/z6v1iS5epkOy5ge8NMwsy6cgMvT5Ge7yi+G/Mxvic5webfDvO9QF4i4EmKo9cHHk3i6l0AkmAf1FQkJOZBkO32JFfjSKvxQwkvypb9JaOpoYEedbhY3lFicKRJhBNf7qeooBJAwt8KU=
  organization: Modern Agile
  space: development
  on:
    repo: modernagile/modernagile.github.io
