language: node_js
node_js:
- '6'
before_script:
- npm install -g grunt
- npm install -g grunt-contrib-qunit --save-dev
script: grunt --base tests --gruntfile tests/Gruntfile.js
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: modernagile@gmail.com
  password:
    secure: UzGR4eP8c3O9FxuWDa7bKw0RSVV9pf71kESkQqbEb4xVNCTuu2wTaPWPm/lTH+62ybE0rfzBecWy2xLCRb0GnCcwWqUKT+72SdedZvXKdh1n3VTvgKLaRvduw8/JMl4GlV7ATflBiH69zkiJEqoVmQtrBbQd4YIy87ujftV0DGkP4twwnF+fZrO19vBPwdHT7p31VylujssAJuLiYxuEEozY+AaPGzy+LOHPztjKx/3JiJmm3TCKiBX6AalnP3T1SnW1jLIBcswHj4POeKzsQWfqujzQdSyZfRMP6XCWZZSwWH3q/fh4UHksfDa0Ivs9JX2RjxaUyUTO7woQJpIBmwHCFrOt4ygZO52glNB0nu2kGKeFl5dhZNVX3SnbEabDrD4cAP8W3O3iC/7YgVKMy6SQoz3Knh2CD8cQFghv3SoR+ENKJgihUXtDKm6weQ/M4BnbTag4dsUHvnCsYCu/NSxlIFw99drgwlGU1pJUAugyGFeWudQ86J04s7Onv8K4X5QaEBd3b2AhKDxEZoXaSde+ptEputs/jrvgVNzDJCdGIVYoBJifvSLBUEgH8CEhFnIv/yCdRATgMhPDY+Yy8gt6N9sYM/rsZe1r4DLyzqCmdVJhfKqE8t7Usgfyp0l53gbhPe8WElhbjAt3JNLGuVrv6ZwwD3clqdrzuk1KjCc=
  organization: Modern Agile
  space: development
  on:
    repo: modernagile/modernagile.github.io
