language: node_js
node_js:
- '6'
before_script:
- npm install -g grunt
- npm install -g grunt-contrib-qunit --save-dev
script: grunt --base tests --gruntfile tests/Gruntfile.js
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: modernagile@gmail.com
  password:
    secure: mhn82iJbhjap2/WfbMVQqDTXshXnCPh5B8pYZ0x8/fQq+kLUgTibIxtOnB+1WvpPPsC9vqFnWQwSbDOgPgS2wl5rlEA/R3FDdGrRKuOaigrmAeF5KO596aFpffBGi47EFZ5W9wiKm12pbA7wzMsK4OI+wlKjmwGCZKVTXb3gKt+VDDHj0I3JRgptThG9VvMM4rKr/9GK3yPl6FAhoSMy9K7u5NZzUf4cf67Htj0L0DDY+YbbVMO8vtuN/LVK7PFwbQSk5mLie0ChxhmzpOnRzFeh5Un3lq4hikbrZEIFCZ8FigzugabF4gd0TZmsnkZenThaoVDgxJEESJdvZZIS7vJEj7XTmy+1jXm5FqAHFU9G2jCFkxfH6OTodqYrb95J5sClu3SnikF5qn2QaijjCUX/FODGA3fjG1bqDYao/cEecT7FkmUJQYf1ckFvdyXY7C3vIzslxcqh3CBxRGgoBvh1yPeoIlNoR5yXa7p9OUzDklaSNwPHz7xXHqQsmhnPsFGkZxyKBz8iSecbN4+CK6dD6NWtsjn5Jw404ny6IbK4jSJyjlkvLPmJRdYLNbWXNB1WLlzgoVhH+TVJk//zGaosNtUmkJUZbX9Cl/s4H3UQ7kSLReifwLy7DAvTpunTaqz6ICHIhAYZlgkYaR1FlZlXHnXcsO2O6PQhmPhLdfo=
  organization: Modern Agile
  space: development
  on:
    repo: modernagile/modernagile.github.io
