language: node_js
node_js:
- '6'
before_script:
- npm install -g grunt
- npm install -g grunt-contrib-qunit --save-dev
script: grunt --base tests --gruntfile tests/Gruntfile.js
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: modernagile@gmail.com
  organization: Modern Agile
  space: development
  on:
    repo: modernagile/modernagile.github.io
  password:
    secure: ROYCfz7Jg7HfYbTEXDAO44OK3ePpWOtWXfjWDVWg5FFPEeSN0xZ+1VT+fWUh4FZrFYpef4lgkEg0BM4qBhSV2rcc99PtjPZbn75h5vQ0ZsW+7Jqju6SlknwomsctJgtIzHCbAxXqRGV5GDGEdksNMp/sePBF1EOQdPFuI14slk4EfLePzdQmSK20LEUPvgWIGZwqzuH7lCd61Pp32i4ugglZ/Cw5LmgOPEYbDKZ4IlIBMdITLa2pCP5EKPA8SIKfzVnsJgD0It0A6i7xxdmWhWNf4AxmaCMcxyry5IRzhhyEjeopAUKhBJ+8G89XXb2Rc4F8WP4o3lac89hunTHFZfMtUetkpzHXhC10T+0D2FvglkEofI5l8q3I6YAOQd/V6WcwwINrF4h83r0cB/5tCpo/W5nvhR/wBWuubYiivGEoGBwgbBUofXKVNqVRUCY9gmuf6Rr5nbud2OLCBEW/zEq3VodN9G7XcNCEMix/liHpZinFHlz6OT9YGwLMSrMhKaMEZz9DlGPsNwNnHUXPS2+dvYe+TdpvRSzMQy/fkbx0rOwVfNNYdBFL97dMnksExQ9FstF2H3tXXMBtVDkcRAmhMaep+G/RM7YdtjrVEoa60zsj4WpyuZeb535YAP5hCHIZA84VUT9+L5RFYZB/hgKdyDBtWeEAKf3Kd6GZpHo=
