language: node_js
node_js:
- '6'
before_script:
- npm install -g grunt
- npm install -g grunt-contrib-qunit --save-dev
script: grunt --base tests --gruntfile tests/Gruntfile.js
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: modernagile@gmail.com
  password:
    secure: HJ1mreg/1LuF44mw3Senqtz6ro8ftKBSIVt/xdoW5lJF9eKNJ4B+JEO6/1F71T7PhH1o3L1b/TJC9PublySFofdeZmaf84ILeTGsmcrlq9Lq3EZkv+PPywpCMAVxggf9xR35hn+wJ7/kr7BCoeoUZKPMkhvsYBcvQUEL9t7VZmoL0nytnVfcFohMbIlji/9dtWJOpbXX3fuOeEZ4Ucnq0VoiXfqeKl8wXL4uuPYXkX7vZ3xaNNABUHbASBZbj39KAQLxAVUoD/U53N1e7wjKKWzYrxwducvLNfwK1S1PSlwwJJPZ6G5jit4aVCMKH3Yt6JeZxjDwGV+KBd9pvoBUNZYbDl/igppQj022xd0HXK8lq4f8yvAylkvTRV1Pdmc1CxDfiatA4bH6pIu9OHUsemsmZ9u7HAqyNq3ocnHmvkLzi6yVn6fufwNQwRzTlmhNEjUY8v4Jtp/d0p6TA7183kh3WgjnqQ1EkdLTna7ZkbSk94AgzCdg1Ylz/Cjz1BBhjJvMJ+eAhPd318CF35EJKKThiU/zBanlm9+3rewg29PDR7cqz2YcjnofNMUUJU0UfStna+FlyVjprQNRxYIgT5kBLDU5ErEOiZT/Q7nyc6miijH3ept+QZBE8cWeSK55keFhPvqNSkdFO7MqXegn1SShYNHcUuub2GyfHo8ZfsE=
  organization: Modern Agile
  space: development
  on:
    repo: modernagile/modernagile.github.io
